info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: INFO
  profile: DEV
  useJson: true

management:
  health:
    rabbit:
      enabled: false 
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
  info:
    env:
      enabled: true 
    build:
      enabled: true 
    git:
      mode: SIMPLE 
      enabled: true 
    defaults:
      enabled: true
  endpoint:
    auditevents:
      enabled: false
    beans:
      enabled: false
    caches:
      enabled: false
    conditions:
      enabled: false
    configprops:
      enabled: false
    env:
      enabled: false
    flyway:
      enabled: false
    health:
      enabled: false
    httptrace:
      enabled: false
    integrationgraph:
      enabled: false
    loggers:
      enabled: false
    liquibase:
      enabled: false
    metrics:
      enabled: false
    mappings:
      enabled: false
    scheduledtasks:
      enabled: false
    sessions:
      enabled: false
    shutdown:
      enabled: false
    threaddump:
      enabled: false
    heapdump:
      enabled: false
    jolokia:
      enabled: false
    logfile:
      enabled: false
    prometheus:
      enabled: false

server:
  port: 8171

spring:
  mvc:
    servlet:
      path: /
  
  security:
    user:
      name: serco_cks
      password: temporary
  output:
    ansi:
      enabled: never
  application:
    name: ONS ContactCentreService


address-index-settings:
  address-query-path: /addresses
  postcode-lookup-path: /addresses/postcode/{postcode}
  rest-client-config:
    scheme: http
    host: addressindex-api-beta.apps.devtest.onsclofo.uk
    port: 80
    
case-service-settings:
  rest-client-config:
    username: serco_cks
    password: temporary
    scheme: http
    host: localhost
    port: 8161
  whitelisted-event-categories:
      - FULFILMENT_REQUESTED
      - FULFILMENT_CONFIRMED
      - UNDELIVERED_MAIL_REPORTED
      - RESPONDENT_AUTHENTICATED
      - SURVEY_LAUNCHED
      - RESPONSE_RECEIVED
      - REFUSAL_RECEIVED
      - UAC_UPDATED
      - QUESTIONNAIRE_LINKED
      - CASE_UPDATED
      - CASE_CREATED
      - ADDRESS_MODIFIED
      - ADDRESS_NOT_VALID
      - ADDRESS_TYPE_CHANGED
      - NEW_ADDRESS_REPORTED
      - FIELD_CASE_UPDATED
      - SAMPLE_UNIT_VALIDATED

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 35672
  virtual-host: /
  
queueconfig:
  event-exchange: events
  dead-letter-exchange: events.deadletter.exchange
  
domain: localhost

keystore: '{
  "keys": {
    "fdc4d96ce6a8fac00d3eba192af1574ffda1c7f0": {
      "type": "public",
      "purpose": "authentication",
      "value": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAux4JMONFvD3zWhZCjYXs\nFKDTfAlJMiwdZO+ZW8paKiW22vA8Cd6G4MzTRNPK+Mz3K72+G659PdLg7/thtEmG\nZYDfHl+V8nlAHnKBBgx6lH2/3zpreMPh6pH6vKiU7PJCWGsE4P5xiZJLK7VOUD6q\nsAL1B1oFC6ekN1yIJsyCEuFRoauRDUY7LxONrI69z2cw4FyigeZiLRFyMsnnbogQ\n/shRyA6gPiZ1KWp1m/6VzPpTeZoNHY2b9CGuEpSyrdWy/xHc0QsxBSxXqWGqAQYm\nbQ8bmaCO3dAmpni+6pQVpzFLGF3C/cy994Qb611XYBhwz1D3yWm6+pOG1pAvJZSd\nt5U0m9kKjoaKWVc1FpBkQ8ep8Tx4wIhC2fuLdFMiB1jwvtmgHQncnPQM0hK7YPbL\ngIjtp7LEXOhp5cW/6QF1u2sgP2pdBngZMqk64PE1yor4H3t0Zwy+kalSnLYJG10d\nLNlPdRGy5iKxt5eeA/ZFUkQyNB28SvMQYrfR/gush4f5nOh1NtQNomWClnEfiTOC\nnmEVwZKWVTk8O0/s3St5HYN9+Az6Q3/emB9ojQXYfMGRrdtAqDlFV/kjqlOIrULI\ngEp7OqfZT2TZqc+4g2JeenvIdZluVu2J2HPAMBEN2RThcIpTe1SPsctCpxhQc8FQ\nSTa26S3nUk9mSyv/EeFg7akCAwEAAQ==\n-----END PUBLIC KEY-----"
    },
    "e27ddb0e5dfef75f82e2cd27c45e59cdf7515bfb": {
      "type": "private",
      "purpose": "authentication",
      "value": "-----BEGIN RSA PRIVATE KEY-----\nMIIJKAIBAAKCAgEAwXgsFT6ZP/l4K1f9C8bbFe9d2X/B5pKsEOGs74ICkUUwCVzx\ntFaHWXDk+DEWkYmN0SU33qrZu+oAmNThHjF1G8P/lnjykkCcVfusmBQA2xxGgOEH\nYlHk42DXvmTt9/t9p0WygvGq3eWRtEyfMlePXQH1TTfso1kX0L46JoGshqSKEIhs\nRK/N0BqqMw0kZXVF0joVx5NmhvS+LbDfyZ421tkYKX71RbnoOEyZV7AKpNOUp5jg\n2KcS+nPzUdrG9xx9bpxGSa+7NSTcBaco+sQZWLEsaT7b0gawu1W8/mWEWIrLnlfV\ndYk1tUIeH6/ByTOiuRa3OwP33x3trn1/5LXSAq3jT/+ZleRkg+thTvcBjMXw4MlL\nWQjsbRCR1ulNsSS12LGmiwTGx+FVYzCmPtZo/SgjDYx1qtgBqTM9XRAkyb38k3O3\n1CKbY4knHnHMvieu1P3zg6S6eLdNrE6A5vN9l8VlZoM3wbcQWWisT5hGhtzsIg98\nxnPh5ZenTfdpOU8kg1PpiJ9zrfdmXH4EHovqND8Nr4YPKc6noW7xLX6RXYf0KmSQ\nW9Yxvb7c799f6ty94wFYUlPlWXw4ASVF9gEUoqIzmVku6fkFfoJJAIILSJvaSon6\nIYJ/uDwxPKGiwvB2U/8YrTBR74M/UDbMRzG2aU3NSX0QDcX+2E0i1y6nmBsCAwEA\nAQKCAgBfYZWqK6B2L9GU3N4+Th145PfJ4PiBalI2SGxv8BK/9/JEy3PGStqTt9rK\nmbjcq4olUEoJFwYdZLJCpsENl6h6tdhuINbGT+BDa76dg08gtwHzS/3N9T3486ep\nkCzaEzzRmMT3VZm9qA57a0MZGJ3vZqW/GhEqPyREn2Qf09Jw1vHSUM+/1USMknjS\njmohMv3nNQfDyuHDKyoPcKIDzmKO7ZzB6HuXkp3wE6ON3ZaByGYDcpV3encazsto\n0YlCDuOwAo+MiHytKKzohI7pgoBUf5S7lmfdVbsPwKdabEYhONxGBluQhMLbx+r+\nCDJrtW9F/PL8v2oWr7ScT/cblKAiIfxoGgjVdB2D5nz6hYtEQuKjDdxIV6VRod4D\n/PATlmXItNZ+BMZR/thrxcsoA6FzpGim0ZVnxnuj3WZWpFa70ZyexHvgeKLhsZ2/\nz2UJebnagxw60ZXFWJIrCMU9UVXxkdWPjWhCxcBklikTuLvag6Mn5Zy3T9KeqpQH\nED6ehTrHCDDwXFhgTw+8iyYOfrQ3kPPd8IfpDxL64d+S+c8GGYOzoJoqWEw6fMjv\nGP2uDAI6CtdwrDJ20oC1FA2RhQq7o1tGiE8cCLtv9/G88hFbqWegt85j+rXptUiF\nzaw/mGLdV/3KIaMvxMxWPunbTeEBfdd1BFNfmA48v9iqG3RB8QKCAQEA74SFZI5z\nU+m1doW2U7KMsfTXvwX2dRgS1iaMHVnyAyWGOMa4wLVYT3hG3hdtA3G8xRjL6Ua3\nQrS+XokST7b89u4mK+QfM3nVmAU5g3kWhJh8cBT0hm+KwvHJ536tvx7fa5DhY5aA\n/bNOYj3bNMw+jDkk6zQDAe6sPZZIMaE4XeFn6ofwbNV+kxgT0jMoxoe67C3gZkAH\nDBAU03QE9onObaP/1XaJJNY8m+GzH/GMwKrynsQRyoyswLEMYdvo2ZGTxKVz57lV\nkx/qYpKELQddZvSo60PMVIAoGjoxYVQwq5yGE0U6yNnRn8Kru61uAHPAfLtbVLva\nc6sFXS37Ljc7HQKCAQEAzshwc5QNfzMJoJJALb7EYhWw9h6ba1w52Cx2RZroM5IC\nTMOXi2wSVe3S418fi3yO0/3Ssb6a4B3Jf1p9WBm/t6Jd3nl0FhIuRdIIUq0FqgBt\np3CRs+kaDXavFYIObisBgALgN6OIhj/RyIGM879Y8TX6xkcr5qDZoSoH+RxNCdh5\nV4nO/BWVThaykPOijhtB9nI5OquMPg05wVOiQMywpUG4lrFnK7Qgq8noegyODDmu\n6i59Y9AaBKF4eSsYv8dh+sTZZjH9354rNY024OPM0qeHKSuI+R6SPyL2OKsi8T23\n948p1PEwSVjmgNsqlQL2KBt2jMrkLEP4mpB89BuClwKCAQB+nto9/KivVb/etnVa\n7es/MKbVj3tpD571o08zPReZ3j6EyVlmVvgmmvkr88pnpbsbny49VmsPUqnJJEGP\n7rbwe5mmXmS4O9JVGX38KQlkc5BlWE6ku1bqFBSe0vNbNCD8pozgrvHmLOJlQTof\nQVJXouYHiWmFnf1kWYw04HwB9WWQMOlDP+I4NORVnUITIjIJJX+ZzoNrNx0rZAwz\noUqF38shuBZsaO2Fot2lJ3c3a6fzksetAo1ZGL/pA+6nBjTOIoGRoQLCUn8AOWCy\nxU/1W6XpKeBdU5rfsp/kSjOopYijq1eWUsBk6u8KunaKuqapygpQUzb7KxAc4HAH\nUJ9pAoIBAGBQ4IAVUAwVe8B9HsOv/c0qCVk6fG4PcSoN27EkLFAJDGUxHZ9lYU0B\nD5+0qP7Rr71ylvcPrxgBB9/4CDZHGBOy30JHFBlLsp327MWFrgO3W1wIhPVl+CqZ\nQ4gjIhGSmopDzKhd1bOielaIcVz/nbAM0pgUgpBUD8qPx1LzKbcSS8LIf87PRtIu\npFH8CZVjgOAH6Dw5t4MXqfUwvXytWwI+kHowe7vRlP4vd8eRnYB4Rc7yhJk/Tz8k\n7vaRal+5wRuLITAGzRehlsLE2fD6amccfUph6tUOtlQONt3CaO4xL0VyO6viA/nG\nHOecLkNmM74OvLNrtcggiOWFs44IWlUCggEBAN50BDQPoZFvJIIWqV8VuEfAnb5O\n4lxQ8PBJis9gfImO+AgEZl54guTEwD/bxXJqVuzSPM+dFkhvpbqKF0/Ikdgrj9SS\nkrg8eU/iLdwOtthz+1Ev44X6RbTrOAhtLeiFSNCSh9wSc+IMiHVrUAh//SIJdX7n\nXw2ZgcCREGt+F6EHQc4EBSwURtcJSOo4O0ILu+4B/rp/9b8R+ojsxdaH6l0LYoGF\nWPeaW4eWB+5RQ4JhA7d1BQDtTbVurGGcQPH1tZ1ucAafRz0yGcXsp9lDz87SjXDq\n0PMLupbFDLSrpZt25ePBWSYS36s9pLNpCiEieIDtI+2ZD2YRmIi7xkDJdTA=\n-----END RSA PRIVATE KEY-----"
    }
  }
}'

eq:
  host: www.google.com
  
report-settings:
  cron-expression: "0 * * * * *"
