info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework: ERROR
  profile: DEV
  useJson: false

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    enabled-by-default: true
  info:
    env:
      enabled: true 
    build:
      enabled: true 
    git:
      mode: SIMPLE 
      enabled: true 
    defaults:
      enabled: true 

server:
  port: 8171

spring:
  mvc:
    servlet:
      path: /
  
  security:
    user:
      name: admin
      password: secret
  output:
    ansi:
      enabled: never
  application:
    name: ONS ContactCentreService


address-index-settings:
  address-query-path: /addresses
  postcode-lookup-path: /addresses/postcode/{postcode}
  rest-client-config:
    scheme: http
    host: addressindex-api-beta.apps.devtest.onsclofo.uk
    port: 80
    
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 35672
  virtual-host: /
report-settings:
  cron-expression: "0 * * * * *"
