logging:
  level:
    uk.gov.ons.ctp.integration.contactcentresvc: DEBUG
    uk.gov.ons.ctp.common: DEBUG
    org.springframework: WARN
  profile: CLOUD
  useJson: true
  
management:
  metrics:
    tags:
      application: ContactCentreService
    export:
      stackdriver:
        project-id: census-integration-dev
        enabled: true
        step: PT1M
        